Fixed css for cart and products
Noya-19/WE-Group4 pull request #18
Opened 2021-11-30 21:03 UTC by sahag98

2021-12-01 20:25 UTC, Noya-19 requested changes
- [ ] Change cart colors to not blend in with the main site
- [ ] Add white background to each product

2021-12-02 01:03 UTC, Noya-19 requested changes

2021-12-02 01:03 UTC, Noya-19 commented on client/src/components/ProductCard.vue
> +                        <label class ="image"><font-awesome-icon icon="fa-tshirt"></label>
Add closing tag.
When testing, no images show up. Check to see if works

2021-12-02 01:51 UTC, HeroofLight555 approved these changes
Looks Good

2021-12-02 01:59 UTC, sahag98 reviewed
Fixed

2021-12-02 02:00 UTC, sahag98 reviewed
Looks good

2021-12-02 02:05 UTC, merged