Database controllers - WE-009
Noya-19/WE-Group4 pull request #20
Opened 2021-12-05 20:43 UTC by sammax12

Completion of database controllers.

2021-12-06 01:02 UTC, Noya-19 requested changes

2021-12-06 01:02 UTC, Noya-19 commented on server/src/controllers/BankController.js
> +            const BANK = Bank.update({
Meant to be delete?

2021-12-06 02:29 UTC, HeroofLight555 approved these changes
Looks good to me!

2021-12-06 04:40 UTC, sahag98 approved these changes

2021-12-07 00:45 UTC, Noya-19 approved these changes

2021-12-07 00:45 UTC, merged